spring:
  config:
    import:
      - classpath:application-logging.yaml
      - classpath:application-db.yaml
      - classpath:application-cloud-stream.yaml
      - classpath:application-springdoc.yaml
      - classpath:application-security.yaml
      # - classpath:application-cache.yaml
      # - classpath:application-client.yaml
      # - classpath:application-resilience4j.yaml
  application:
    name: sample-api
  main:
    banner-mode: off

server:
  port: ${SERVER_PORT:8082}
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

app:
  security:
    geo-admin-role: geo-admin
